### ISSUE TITLE
Upload to Huggingface?

### ISSUE THREAD

**Issue by BigSalmon2** [iamarkaj/Split-and-Rephrase#1]
Would it be possible for you to upload your model to Hugging Face?

**Comment by iamarkaj** [comment]
Hi @BigSalmon2 

Thank you for your suggestion. However, I have uploaded all the models to the google drive. You can find them [here](https://drive.google.com/drive/folders/1RmVMuqlxBKkgmbRU5ww1E_LRibFcdtqt?usp=sharing) in case you need them. Apologies for the delayed response. 

Regards,
Arka
