### ISSUE TITLE
linguistics.main

### ISSUE THREAD

**Issue by mbaxamb3333** [iamarkaj/Split-and-Rephrase#2]
Hello, @iamarkaj ! Thank you for putting in the work with regards to this repo. 
I would like to ask you the following:

In your main.pay file, you reference linguistics.main. Where does that might come from ? 

Thank you very much

**Comment by martinve** [comment]
I am having the same issue of wondering where to find "linguistics.main" 
Can you please tell what you did to resolve this issue.

**Comment by iamarkaj** [comment]
> I am having the same issue of wondering where to find "linguistics.main"
> Can you please tell what you did to resolve this issue.

The bug is fixed now.
